package io.avalia.samba;

import org.junit.Assert;
import static org.junit.Assert.assertNotNull;
import org.junit.Test;

/**
 *       *** IMPORTANT WARNING : DO NOT EDIT THIS FILE ***
 * 
 * This file is used to specify what you have to implement. To check your work,
 * we will run our own copy of the automated tests. If you change this file,
 * then you will introduce a change of specification!!!
 * 
 * @author Olivier Liechti
 */
public class CuicaTest {

  @Test
  public void anCuicaShouldMakeTicutucuNaocutucu() {
    IInstrument cuica = new Cuica();
    String sound = cuica.play();
    Assert.assertEquals("ticutucu nãocututu ticutucu nãocututu", sound);
  }
  
  @Test
  public void anCuicaShouldBeDarkYellow() {
    IInstrument cuica = new Cuica();
    String color = cuica.getColor();
    Assert.assertEquals("soft white", color);
  }
  
  @Test
  public void anCuicaShouldBeAwesome() {
    IInstrument trumpet = new Trumpet();
    IInstrument flute = new Flute();
	IInstrument ilu = new Ilu();
	IInstrument cuica = new Cuica();
    int trumpetVolume = trumpet.getSoundVolume();
    int fluteVolume = flute.getSoundVolume();
	int trumpetAndFluteVolumeCombined = fluteVolume + trumpetVolume;
	int awesomeSound = cuica.getSoundVolume + (trumpetAndFluteVolumeCombined * 2);
    Assert.assertTrue(awesomeSound > 1000);
  }
 
}
